### ISSUE TITLE
Support for 418.67?

### ISSUE THREAD

**Issue by GoatCheez** [keylase/nvidia-patch#107]
Is there any chance this can get updated to also support version 418.67?

**Comment by Snawoot** [comment]
Hi! Which OS and driver type we are speaking about? Could you provide a link?

**Comment by Snawoot** [comment]
I've found only one driver with version 418.67 and it is a Tesla driver for Linux. Since [Tesla has unrestricted NVENC sessions](https://developer.nvidia.com/video-encode-decode-gpu-support-matrix#Encoder) we don't need to patch it, so I'm closing issue.

Feel free to reopen it, if you feel different about it.

**Comment by billylindeman** [comment]
@Snawoot I think this is the version that is installed with CUDA, its what is currently running on my lenovo x1e

**Comment by Snawoot** [comment]
@billylindeman Thanks, now I see. Yes, it's a driver bundled with CUDA Toolkit 10.1. I hope it'll be patched very soon.

**Comment by GoatCheez** [comment]
It was installed to support CUDA 10.1. It works with the 1050Ti in the machine. I modified the patch script to add the two lines to support it, and it seems to be working fine.

**Comment by Snawoot** [comment]
Fixed via #110
