### ISSUE TITLE
Unraid help

### ISSUE THREAD

**Issue by r4czo** [keylase/nvidia-patch#165]
Hello i get stuck trying to install this patch on unraid where it gives me this error. it seems people here have got past that problem but there it no one who have explaned what to do to get it to work https://github.com/keylase/nvidia-patch/issues/43

ERROR: The kernel header file
         '/usr/src/linux-4.19.56-Unraid/include/linux/kernel.h' does not
         exist.

**Comment by Snawoot** [comment]
Hi!

How do you get this error? After which step?

**Comment by r4czo** [comment]
when i run this ./NVIDIA-Linux-x86_64-430.14.run

**Comment by r4czo** [comment]
seems like this guy 3urningChrome had the same problem but somehow got past it

**Comment by Snawoot** [comment]
Well, that means you are failing to install Nvidia driver due to missing kernel headers, not our patch, thus your issue is unrelated to our work.

Check out [Unraid Nvidia](https://forums.unraid.net/topic/77813-plugin-linuxserverio-unraid-nvidia/) plugin and see [related video](https://youtu.be/GOhHiFAXwOE) from Spaceinvader One, maybe this will help you with Nvidia driver install on Unraid. We are focused on patching work here, assuming driver is already installed.

**Comment by r4czo** [comment]
well i have installed the driver using unraid nvidia plugin i did everything exactly as in that video, plex can use my 1070 but limited as you know. Do i need to install it in a specific directory?

**Comment by Snawoot** [comment]
If you have driver installed, then all you have to do is to run patch.sh

**Comment by r4czo** [comment]
wow thank works great now :)
