### ISSUE TITLE
Question: visual optimization 

### ISSUE THREAD

**Issue by Saentist** [keylase/nvidia-patch#206]
Hello,

Is there a chance to optimise look of bash visualization.
**dialog** can be good beginning

Also is it possible to add test to confirm success of patch?
ex:
```
#!/bin/bash
function pause(){
   read -p "$*"
}
pause '
#####################################
# Test 10 session of nvenc encoding #
#  1920x1080@60fps for 30 seconds   #
#####################################
Press [Enter] key to continue...'

./ffmpeg -loglevel repeat+level+verbose -y -f lavfi -i nullsrc=s=1920x1080:r=60:d=30 \
-c:v h264_nvenc -f null - \
-c:v h264_nvenc -f null - \
-c:v h264_nvenc -f null - \
-c:v h264_nvenc -f null - \
-c:v h264_nvenc -f null - \
-c:v h264_nvenc -f null - \
-c:v h264_nvenc -f null - \
-c:v h264_nvenc -f null - \
-c:v h264_nvenc -f null - \
-c:v h264_nvenc -f null -
```
this script need ffmpeg with nvidia support in same folder /need optimisation/
session is set to 10 /need session number choice / 
size and fps is also fixed
concentrated result of test
hope finaly to post result as in https://github.com/rigaya/NVEnc ;)

**Comment by Snawoot** [comment]
Hello!

> Is there a chance to optimise look of bash visualization.
dialog can be good beginning

`patch.sh` is used by wide variety of systems, including minimalistic docker containers and Unraid appliances. Also this script is used by other automatical scripts (e.g. autorun userscripts of Unraid and [Cloudbox recipes](https://github.com/Cloudbox/Cloudbox/blob/7851f82f2c33f9e1336461b5264999f5e3b3f240/roles/nvidia/tasks/nvidia_patch.yml#L13)).

For these reasons `patch.sh` is maintained with following constraints:
* Compatible with unattended/automated operation.
* No filename/public URL changes.
* Minimal amount of dependencies. At this moment patch requires only `bash`, `sed` and `coreutils` that exist on almost every Linux installation.
* CLI changes should be rare as possible because such changes may break [things for other people](https://github.com/Cloudbox/Cloudbox/blob/7851f82f2c33f9e1336461b5264999f5e3b3f240/roles/nvidia/tasks/nvidia_patch.yml#L32).

If you feel like improvements you proposed are absolutely needed, you may develop separate wrapper which invokes `patch.sh` as an external utility and shows fancy UI (maybe even graphical). There already was some work done to allow machine parsable interaction with `patch.sh` (#163), but if something is missing we can add it upon request.

**Comment by Saentist** [comment]
With other words, if need friendly GCLI need other bash script with in background will call current `patch.sh`
