### ISSUE TITLE
Error Question

### ISSUE THREAD

**Issue by Mr-Rog** [keylase/nvidia-patch#228]
Hello,

My question is: ... I try everithing like how I see here
I use 440.44 Driver, also try with ppa
But when I start the Patch I get this 
./patch-fbc.sh: Zeile 7: Syntaxfehler beim unerwarteten Wort »newline«
./patch-fbc.sh: Zeile 7: `<!DOCTYPE html>'
I googel it but dont found the solution
Error means Syntax Error bei unexpected word newline
Sorry for asking but I dont found the problem.. try and try
Cheers and Thank you for Helping

**Comment by Snawoot** [comment]
Hi!

This issue is duplicate to #61.

It looks like instead of downloading `patch-fbc.sh` you downloaded _HTML page_ showing `patch-fbc.sh` contents.

Here is available options (alternatives) to resolve this:
* Checkout repo with `git` and use `patch-fbc.sh` from working copy of repo.
* Download ZIP archive with repo contents using Github UI and use `patch-fbc.sh` from .zip-archive.
* View `patch-fbc.sh` via Github file UI and hit Raw button. Then save raw file contents.
