### ISSUE TITLE
Any way to avoid this patched nvenc being blocked by Battleye anti-cheat system

### ISSUE THREAD

**Issue by dannytrigo** [keylase/nvidia-patch#309]
Hello,

I've noticed recently that Battleye anti-cheat is preventing NVEnc being loaded when it is simply patched for more encodes.  Does anyone have any suggestions to get around this?

Thanks

**Comment by Saentist** [comment]
https://www.battleye.com/contact/
Ask them.

**Comment by dannytrigo** [comment]
I did... but I was perhaps wondering if there's a way to have two versions of the encoding dll and somehow statically link the patched one to a particular application like Plex, and allow other applications to load the default one?  But I appreciate its not really a question about the patches or patch tool itself.

**Comment by dannytrigo** [comment]
I have tried copying the two dlls to my Plex directory and patching those copies, and that seems to work.  I see in process explorer that the 32 bit one in the same directory is loaded and used.
I have yet to confirm if gaming captures will now work correctly without Battleye preventing loading the encoder dll, which is now standard in my system directories, but will confirm if it works in case anyone else runs into the same issue.

**Comment by amnesia0287** [comment]
I doubt they care about the number of nvenc being unlocked, they are likely just doing hash checks of the various driver files so people cant do like see through wall hacks and whatnot.

As to using multiple copies, it really depends how nvenc is engineered, since normally once an assembly is loaded into memory it stays there and it doesn't like if you try and load a different version. (I'm only used to managed code so if this is wrong for unmanaged then oops).

Anything with strict checking is always gonna have issues cause once you change the file the hash wont match and thus the signing will be invalid... etc. Thus are the risks of using modded drivers lol.

It would probably be easier to just make shortcuts to patch/revert as needed, but if plex for some reason loads a local copy first if its there, thats fine too.

**Comment by dannytrigo** [comment]
Can confirm it worked to have a separate copy of the dlls in the same directory as the Plex executable
