### ISSUE TITLE
New driver support (i386 nvfbc libraries)

### ISSUE THREAD

**Issue by chkuendig** [keylase/nvidia-patch#350]
**Please provide details about your environment (please complete the following information)**
- Nvidia driver version: 450.80.02
- GPU Model: Quadro P400
- OS: Ubuntu 20.04
- [x] I'm willing to participate in testing of new patch version

Do you think it would be possible to also provide patches for i386 versions of the nvfbc libraries?

**Comment by Snawoot** [comment]
Hi!

I'm not going to handle any i386 libraries for Linux for because:

1. It's multiple decades old legacy.
2. There is no reasons to use i386 on Linux except for proprietary for which see (1).
3. Linux distros are dropping i386 support (Ubuntu dropped 32-bit edition).
4. I can't allocate additional resources for this stream of drivers. I'm quite busy these days and I don't even have working GPU now to do tests.

However, it is completely possible if someone will handle it and take care of it's support - I'll be glad to accept such PR. So, in practical terms it's unlikely.

**Comment by chkuendig** [comment]
Thanks for the fast answer. I completely understand that this might not make much sense to invest in.

For everybody else trying to play around with i386: I hacked a quick lib together yesterday night which works using LD_PRELOAD  for any architecture (tested with the SDK samples): https://gist.github.com/chkuendig/fc26f4fe0b378012c697fd46dad1a73d
