### ISSUE TITLE
NVFBC no longer working in Arch Linux: Invalid external buffer capabilities

### ISSUE THREAD

**Issue by thegamingrestoration** [keylase/nvidia-patch#511]
**Describe the bug**
Since yesterday morning (approx) I get the following message in all the programs that try to initialize and use NVFBC:

> **Invalid external buffer capabilities**

Apparently it only happens in Arch Linux and after installing the latest updates.

**To Reproduce**
1. Updating Arch Linux
2. Running any [NVIDIA Linux Capture SDK samples](https://developer.nvidia.com/capture-sdk), [OBS Studio's NVFBC plugin](https://gitlab.com/fzwoch/obs-nvfbc), or [sunshine](https://github.com/SunshineStream/Sunshine).

**Expected behavior**
This error message should not appear and NVFBC should be working like it did before the updates.

**Output listings**
```
./NvFBCCUDAAsync
Application version: 4
NvFBC API version: 1.8

Creating an asynchronous capture session of 10 frames with 1 second internal between captures.
Invalid external buffer capabilities
```

(All the programs give the same error message).

**Environment (please complete the following information):**
 - OS: Arch Linux
 - GPU model: GTX 1650 and GTX 850M (I had the same issue on both my desktop and a friend's laptop. They both run Arch Linux and have the latest updates installed)
 - Patch commit used: fc546e45d3cbedb79b891ae2a37a0bf96be3a7d5
 - Nvidia driver version: 510.54

**Additional context**

This is a list of the package updates that were installed yesterday morning:

```
librsvg-2:2.52.7-1-x86_64
linux-firmware-20220309.cd01f85-1-any
shellcheck-0.8.0-37-x86_64
lib32-librsvg-2:2.52.7-1-x86_64
amd-ucode-20220309.cd01f85-1-any
linux-firmware-whence-20220309.cd01f85-1-any
intel-mkl-2020.4.304-1-x86_64
magma-2.6.1-5-x86_64
python-pytorch-cuda-1.11.0rc5-2-x86_64
nccl-2.12.7-1-x86_64
python-scipy-1.8.0-1-x86_64
onednn-2.5.2-1-x86_64
gflags-2.2.2-4-x86_64
google-glog-0.5.0-2-x86_64
llvm-13.0.1-2-x86_64
llvm-libs-13.0.1-2-x86_64
shellcheck-0.8.0-38-x86_64
lib32-vkd3d-1.3-1-x86_64
vulkan-tools-1.3.207-1-x86_64
lib32-vulkan-icd-loader-1.3.207-1-x86_64
mpv-mpris-0.7-2-x86_64
vhba-module-dkms-20211218-20-x86_64
egl-wayland-2:1.1.9+r3+g582b2d3-1-x86_64
lib32-nvidia-utils-510.54-1-x86_64
nvidia-dkms-510.54-1-x86_64
nvidia-utils-510.54-1-x86_64
lib32-opencl-nvidia-510.54-1-x86_64
opencl-nvidia-510.54-1-x86_64
nvidia-settings-510.54-2-x86_64
jre8-openjdk-8.332.u04-1-x86_64
jre8-openjdk-headless-8.332.u04-1-x86_64
linux-lts-5.15.27-1-x86_64
linux-lts-headers-5.15.27-1-x86_64
```

**Comment by tobyg0** [comment]
I am having the same issue with an GTX 1660, getting a black screen when using the obs plugin.

`warning: Unable to cleanup NvFBC
info: Switched to scene 'Scene'
info: ------------------------------------------------
info: Loaded scenes:
info: - scene 'Scene':
info:     - source: 'NvFBC Source' (nvfbc-source)
info: ------------------------------------------------
error: Invalid external buffer capabilities
`

**Comment by jailuthra** [comment]
The shipped 510.54 NvFBC driver is exactly the same as 510.47.03 byte-by-byte
![image](https://user-images.githubusercontent.com/1710825/158060354-619b4c1e-230c-44cb-ae15-d6ca2ac0ffe9.png)

I think some other dependency of NvFBC was broken during the arch linux update. It could be other nvidia/cuda libraries, the kernel, or some other package.

Marking it as not-a-bug, unless someone can get NvFBC running on a Quadro/Tesla with a similar Arch Linux setup and 510.54 driver.

**Comment by thegamingrestoration** [comment]
Hi @jailuthra, thanks for the quick reply. You're right, the issue actually comes from these vulkan library updates:

`lib32-vulkan-icd-loader-1.3.207-1  vulkan-headers-1:1.3.207-1  vulkan-icd-loader-1.3.207-1  vulkan-tools-1.3.207-1`

After downgrading them NvFBC is working perfectly again. [I re-compiled the 4 previous versions of these packages and attached them here, in case anybody needs them.](https://github.com/keylase/nvidia-patch/files/8239756/FIX_11_MARCH_NVFBC.zip)
As for this issue, I will report it to the Arch forums instead.

**Comment by abc1012** [comment]
I had the same issue and couldn't figure out why, can confirm that downgrading those packages worked. Thanks for compiling them.

**Comment by xpander69** [comment]
Ohh sorry for posting just another report. Didn't somehow notice this. Hit the same problem

**Comment by insanemal** [comment]
> Hi @jailuthra, thanks for the quick reply. You're right, the issue actually comes from these vulkan library updates:
> 
> `lib32-vulkan-icd-loader-1.3.207-1 vulkan-headers-1:1.3.207-1 vulkan-icd-loader-1.3.207-1 vulkan-tools-1.3.207-1`
> 
> After downgrading them NvFBC is working perfectly again. [I re-compiled the 4 previous versions of these packages and attached them here, in case anybody needs them.](https://github.com/keylase/nvidia-patch/files/8239756/FIX_11_MARCH_NVFBC.zip) As for this issue, I will report it to the Arch forums instead.

Have you lodged this bug against the Arch packages? I'm trying to find it

**Comment by GenocideStomper** [comment]
@thegamingrestoration Thank you for investigating! Can you link the forum post or bug report so I can track this issue?

**Comment by jailuthra** [comment]
Here's the bug report on Arch https://bugs.archlinux.org/task/74211

And I believe Vulkan is already on top of it https://github.com/KhronosGroup/Vulkan-Loader/issues/894

**Comment by h0m3** [comment]
For what i'm reading in the (vulkan-thread)[https://github.com/KhronosGroup/Vulkan-Loader/issues/894] it looks like a nvidia driver issue.

I'm honestly not qualified to really understand but being a nvidia driver issue its possible to nvidia-patch to temporarely fix the issue as an nvidia-patch improvement instead of a nvidia-patch bug?

**Comment by Iglu47** [comment]
I see that patch-fbc.sh has the same "patches" for 460 and above. If all these versions have the same `libnvidia-fbc.so` with the same hashsum, then this change to bump `apiVersion` on 510.60.02 should apply correctly for all these versions.
`objdump -d libnvidia-fbc.so`
```
   12d0d:	48 8d 05 4b 23 00 00 	lea    0x234b(%rip),%rax        # 1505f <NvFBCCreateInstance@@Base+0x464f>
   12d14:	85 db                	test   %ebx,%ebx
   12d16:	c7 84 24 f8 01 00 00 	movl   $0x0,0x1f8(%rsp)
   12d1d:	00 00 00 00 
   12d21:	c7 84 24 fc 01 00 00 	movl   $0x400000,0x1fc(%rsp)
   12d28:	00 00 40 00 
   12d2c:	48 89 84 24 f0 01 00 	mov    %rax,0x1f0(%rsp)
   12d33:	00 
```
It is necessary to change the data starting at 12d28.
`12d28:	00 00 40 00` apiVersion 1.0.0
`12d28:	00 10 40 00` apiVersion 1.1.0
In order to make sure that there will be no accidental replacements, the previous memory zone with the previous command is used for searching/comparison.
`sed -i 's/\xc7\x84\x24\xfc\x01\x00\x00\x00\x00\x40\x00/\xc7\x84\x24\xfc\x01\x00\x00\x00\x10\x40\x00/' "libnvidia-fbc.so.${pkgver}"`

**Comment by Iglu47** [comment]
The problem is that the latest versions of vk-loader 1.3.204 and above do a more correct check and allow to use those layers that are approved for the apiVersion that the application itself requesting/transmitting. In theory it should be safe to bump minimal apiVersion since the 510 driver itself already provides support for vulkan api 1.3.

**Comment by Iglu47** [comment]
The problem is that the latest versions of vk-loader 1.3.204 and above do a more correct check and allow to use those layers that are approved for the apiVersion that the application itself requesting/transmitting. In theory it should be safe to bump minimal apiVersion since the 510 driver itself already should provides support for vulkan api 1.3.

**Comment by Iglu47** [comment]
The problem is that the latest versions of vk-loader 1.3.204 and above do a more correct check and allow to use those layers that are approved for the apiVersion that the application itself requesting/transmitting. In theory it should be safe to bump minimal apiVersion since the 510 driver itself already should provides support for vulkan api 1.3.
But the correct official fix from nvidia's side would be preferable, since patching like the above will "fix" the problem obly for `libnvidia-fbc.so` and other similar potential cases of similar problems in other driver files are not obvious to people who cannot see the source code.

**Comment by Iglu47** [comment]
The problem is that the latest versions of vk-loader 1.3.204 and above do a more correct check and allow to use those layers that are approved for the apiVersion that the application itself requesting/transmitting. In theory it should be safe to bump minimal apiVersion since the 510 driver itself already should provides support for vulkan api 1.3.
But the correct official fix from nvidia's side would be preferable, since patching like the above will "fix" the problem only for `libnvidia-fbc.so` and other similar potential cases of similar problems in other driver files are not obvious to people who cannot see the source code.
