### ISSUE TITLE
Flatpak NvFBC Fail to Patch

### ISSUE THREAD

**Issue by Rakeen70210** [keylase/nvidia-patch#516]
I'm running Garuda linux with the flatpak version of OBS. When I try to run either of the patch commands I get the following error:

`WARNING: Flatpak flag enabled (-f), modifying ONLY the Flatpak driver.
Detected nvidia driver version: 510.54
ERROR: Flatpak package for driver 510.54 does not appear to be installed.
Try rebooting your computer and/or running 'flatpak update'.
`
I have verified that 510.54 version of flatpak driver is indeed installed, I've tried running 'flatpak update' and restarting but not sure why its giving me this message. Obviously I can install OBS through AUR but prefer to use the flatpak version if possible.

**Comment by guihkx** [comment]
Please provide the output of:

```
```

And:

```
```

**Comment by serossi** [comment]
issue is in ldconfig 

line 352 in the patch-fbc

sha1sum "${PATCH_OUTPUT_DIR-$driver_dir}/$object.$driver_version"
    ldconfig
    echo "Patched!"

change to 

    sudo ldconfig

thats it. ldconfig needs elevated rights, but you cant start the script with sudo or its in the wrong context.
all you need is sudo for ldconfig anyway

**Comment by serossi** [comment]
done

**Comment by guihkx** [comment]
I honestly don't think that's the problem, nor the solution.

We are supposed to run the script as root, so any program running within the script will be elevated as well.

**Comment by guihkx** [comment]
To me, this specific issue is probably due to some Linux distros installing the Flatpak NVIDIA driver user-wide instead of system-wide, so when you run the script as root, the `flatpak` command will be elevated and will try to search the driver in either `/var/lib/flatpak` or `/root/.local/share/flatpak` (IIRC), but because the actual installation path is in `/home/john/.local/share`, no driver will be found.

One could think to to run the script as a regular user, but unfortunately the script will also fail trying to backup the driver files to `/opt/nvidia`, due to missing write permission on that directory.

So, if my assumptions are correct, this will need a proper fix and documentation to handle such scenarios.

I say we wait for @Rakeen70210's response.

**Comment by serossi** [comment]
it is the problem and it is the solution. 
it is testet as such, ofc i assume you have write permissions as user for /opt/nvidia

it is not correct to run the script as root at all. many distros run now userbased, so you will always be in the wrong context. 
in such running the script as root will fail. 

simple solution

1. at write for everyone for the /opt/nvidia
2. invoke ldconfig as sudo

if you run sudo as root it will still work, however for any distro running it userbased it will always fail if not.

**Comment by guihkx** [comment]
>it is the problem and it is the solution.

I'm not sure I agree:

>ofc i assume you have write permissions as user for /opt/nvidia

Why would you even assume that, though? No distro out there gives write permission for regular users to `/opt`.

>it is not correct to run the script as root at all

There's nothing wrong with running the script as root per se, but I somewhat agree that it'd be nicer not having to. The problems I see with your current solution - assuming the script is now meant to run without elevated privileges -, is that it currently doesn't address these points:

- The backup file is still needs root permission for being written to `/opt/nvidia`
- The script [calls `sed`](https://github.com/keylase/nvidia-patch/blob/e8be7a508a894872900a44e794c1cfb94b300dfb/patch-fbc.sh#L349) to patch the driver, so if we're trying to patch the non-Flatpak driver, the script will **still** need root access, because the system-wide driver file sits at `/usr/lib`
- If try to fix the issue above by simply adding a `sudo` at the beginning of the `sed` call and then run `./patch.sh -f`, the script will mess with the file permissions of the user-installed Flatpak driver, which will require root permissions for the file to be removed

All of the above is fixable, of course, but I think we should try to use the proper approach.

**Comment by serossi** [comment]
no it doesnt,
i have it running perfectly fine. all i did is give write permissions to /opt/nvidia and add sudo for the call to ldconfig

after that everythind ran fine within usercontext and flatpack was patched and it works as testet with obs nvfbc

**Comment by neromaverick** [comment]
Submitted PR: https://github.com/keylase/nvidia-patch/pull/693

Which should fix this issue.
