### ISSUE TITLE
Error: Invalid external buffer capabilities

### ISSUE THREAD

**Issue by debian-user-france1** [keylase/nvidia-patch#523]
**Describe the bug**
I used patch.sh to patch  it for gpu-screen-recorder but it says now: `Error: Invalid external buffer capabilities
`
**Expected behavior**
It should work.

**Output listings**
./patch.sh first didn't work so I ran patch-fbc.sh and even after a reboot this happens now.

**Environment (please complete the following information):**
 - OS: Manjaro
 - GPU model: NVIDIA GeForce GTX 1660 super _(I **hate** nvidia)_
 - Patch commit used: How can I find that out?
 - Nvidia driver version: 510.60.02

**Comment by debian-user-france1** [comment]
#511

**Comment by Iglu47** [comment]
this already fixed in nvidia-driver 510.68.02
while you wait for this version in your distribution, you can just use this patch as a temporary workaround
`sudo sed -i 's/\xc7\x84\x24\xfc\x01\x00\x00\x00\x00\x40\x00/\xc7\x84\x24\xfc\x01\x00\x00\x00\x10\x40\x00/' '/usr/lib/libnvidia-fbc.so.510.60.02'`
