### ISSUE TITLE
New driver support (version 512.77)

### ISSUE THREAD

**Issue by Zanthed** [keylase/nvidia-patch#532]
- Nvidia driver version: 512.77
- GPU Model: RTX 3080 and GTX 1070
- OS: Windows 11 Enterprise
- [x] I'm willing to participate in testing of new patch version

**Comment by jailuthra** [comment]
@Zanthed can you test #530

**Comment by Zanthed** [comment]
Sure.

**Comment by Zanthed** [comment]
@jailuthra OBS recording with NVENC works, NVIDIA Broadcast works, and GeForce Experience works. I can't do extensive testing, but nothing is crashing and burning either.

**Comment by jailuthra** [comment]
Thanks for testing @Zanthed - will merge.

**Comment by jailuthra** [comment]
@reloxx13 you're right, he didn't actually test if the patch did its job, but i still merged it because i don't have a nvidia machine anymore to test any patches with.

the idea is to get a patch merged in master as long as it doesn't break the driver. if the patch doesn't do actually remove the limit someone will report it. most people just clone from master (or worse the ipfs link which is even more out of date)

i am fine with leaving PRs open too though, can do that moving forward.

**Comment by Zanthed** [comment]
I explicitly said I could not do extensive testing (which was ignored) and the only thing I tested was it basic things worked. I even unchecked the box to participate in testing, but it was (also) ignored and asked to test anyways.

There are no guidelines on how to test patches either. If you want proper testing done, then consider meeting people half way and giving us guidelines or instructions.
