### ISSUE TITLE
OBS crash caused by patched nvencodeapi64.dll

### ISSUE THREAD

**Issue by Bluscream** [keylase/nvidia-patch#609]
**To Reproduce**
1. Remove all video drivers using [DDU](https://www.guru3d.com/files-details/display-driver-uninstaller-download.html)
1. Install the driver and patch using [NVCleanstall](https://www.techpowerup.com/download/techpowerup-nvcleanstall)
2. Set up OBS to encode using NVENC
3. Start stream
4. B00M

**Expected behavior**

**Output listings**
If applicable, add output listings or screenshots to help explain your problem.

**Environment (please complete the following information):**
 - OS: Win 11
 - Patch commit used: NVCleanstall's latest
 - GPU-Z: https://www.techpowerup.com/gpuz/details/77y3e / https://www.techpowerup.com/gpuz/details/5ncm4
 
**Additional context**
Relevant Thread on NVCleanstall's Forum: https://www.techpowerup.com/forums/threads/new-option-is-probably-causing-crashing-in-obs.304160/
Relevant Thread on OBS's Forum: https://obsproject.com/forum/threads/nvenc-crash-crashes-obs.163773/

**Comment by jailuthra** [comment]
Can you reproduce the crash by not using NVCleanInstall; instead using the manual patching steps mentioned in this repository?

**Comment by Lifell** [comment]
He mentioned in the "Relevant Thread on NVCleanstall's Forum" link that he doesn't know how to patch. I'm always using that specific experimental tweak and I have no issues recording in OBS. I haven't done anything with DDU, I just always record gameplay with NVENC and have just done so a few times. Rather unfortunate considering I could've tested it with testing patching the .dll's manually.

Apart from that, I did DDU some time ago to start using NVCleanstall again and haven't used the regulars installers since then. I have an old 1080 Ti, maybe it's GPU related as well? Patch and specific GPU models that causes his issue?

Worthy of note is that applying the patch is more simple than it looks. You essentially download a little application that uses .1337 files to patch 2 .dll files. Those patches have the .1337 extension if I remember correctly and just consist of some plain text if you open them in a text editor. You load the patch in the small application, then target the correct .dll which is made easy in the selection window and then you just patch it. All through the UI. You do that for 2 .dll's which I think have the same name.

No need to really build anything. The instructions are here when you scroll down a bit: https://github.com/keylase/nvidia-patch/tree/master/win It confused me at first that the regular link shows the instructions and what not for the Linux version of the patch while the Windows instructions are in a different tree altogether.

I hope I'm helping and I'm not just being really annoying :P.

**Comment by Bluscream** [comment]
The issue is no longer present with the latest version of all 3 involved applications.
