### ISSUE TITLE
New driver support (version 535.43.02)

### ISSUE THREAD

**Issue by Ludolacra** [keylase/nvidia-patch#655]
- Nvidia driver version: 535.43.02
- GPU Model: GTX 1060 6GB
- OS: Unraid 6.11.5
- [x] I'm willing to participate in testing of new patch version

**Comment by cameronjust** [comment]
Purely from a curiousity perspective can someone provide info about the before/after patch assembly/opcodes?

I used to patch TiVo binaries for later versions to unlock other features and it was always interesting hunting for them with new versions.

**Comment by jailuthra** [comment]
Hey @cameronjust - nice progress. I found the bytecode for this driver version but feel free to give it a shot from next one!

You can run the installer file with "-x" passed as CLI argument to extract contents instead of installing.
The installer is actually a script, you can open it in an editor or even call "---help" :)

**Comment by jailuthra** [comment]
@Ludolacra can you test if the new patch at #656 removes the session limit for you? Use the wiki for steps to check >5 encode sessions.

**Comment by Ludolacra** [comment]
Thanks for the quick fix, yes, the patch works perfectly.
