### ISSUE TITLE
Question: is it unusual to notice improvements for dec utilization as well? 

### ISSUE THREAD

**Issue by rocco-haro** [keylase/nvidia-patch#660]
Hello,

First of all, thank you so much for your work. I appreciate you! 

More curious than anything else, is it unusual to notice improvements in decode utilization after applying your patch? On my Titan V100 I was utilizing 9% decode (through nvstat) for two 480p 30fps h.264 streams. After applying your patch, the decode utilization dropped to around 1% per stream!

At a high level, what does your patch do? 

What would happen if one were to apply your patch to data center gpus, say the T4? Could we apply it to them if they are deployed in AWS? Does it even make sense to do such a thing? 

Thank you!

**Comment by jailuthra** [comment]
Hi @rocco-haro,

That's curious indeed. The patch basically ignores the return value of a function in the libnvidia-encode library (for NVENC) that is supposed to check if it is a consumer gpu (so that it can artificially restrict the number of encode sessions allowed).

I don't think it should effect decoding (NVDEC) at all as that is separate accelerator, so I am as surprised as you are.

As for using this on data center gpus (like T4) which already support unlimited encode session - I don't believe it will make any difference. Applying the patch will still work, all it would do is ignore the return value of a function that was already returning something that would lead to unlimited sessions.

**Comment by rocco-haro** [comment]
Interesting, thank you for the explanation @jailuthra !
