### ISSUE TITLE
Question: Getting an error message?

### ISSUE THREAD

**Issue by quadcom** [keylase/nvidia-patch#706]
I'm not much of a Linux guru so I have been stumbling through getting this running on  my Ubunutu 22 VM.

I DL'd the 'path.sh' file and tried to run it. But the following error message was returned;

```
$ bash ./patch.sh -h
su: user flatpak info --show-location \"org.freedesktop.Platform.GL.nvidia-\" does not exist or the user entry does not contain all the required fields
./patch.sh: line 1: get_flatpak_driver_path: command not found
sha1sum: '"/."': No such file or directory
sha1sum: '"/."': No such file or directory
./patch.sh: line 1: payload:allShortcutsEnabled:false: command not found

```

**Comment by jghake** [comment]
I'm getting the same error on OMV6.

**Comment by jailuthra** [comment]
How did you download the `patch.sh` file? @jghake @quadcom check inside the file you downloaded, I'm pretty sure you ended up downloading the whole webpage :)

Instead clone the github repo (so that you can pull future driver updates) or download the RAW patch.sh from this URL:
https://github.com/keylase/nvidia-patch/raw/master/patch.sh
