### ISSUE TITLE
Question: Increase limit instead of removing it?

### ISSUE THREAD

**Issue by binarymelon** [keylase/nvidia-patch#74]
Hello,

My question is: Would it be possible to modify the patch to accept input to increase the limit instead of removing it?

**Comment by Snawoot** [comment]
Hello,

In theory, yes, it is possible, but much trickier than removing it for good. What is practical need of doing this?

**Comment by binarymelon** [comment]
Just to prevent over utilizing the GPU.

**Comment by Snawoot** [comment]
Some users [report](https://ffmpeg.org/pipermail/ffmpeg-user/2018-July/040609.html) simultaneous transcode of 60 SD channels without any issues. If GPU somehow hits performance limit, it just [processes all streams slower](https://github.com/keylase/nvidia-patch/issues/39).

If you are afraid of GPU overheat - well, it's GPU business to manage hardware condition. If your GPU tends to overheating for some reason, then you may overheat it under virtually any workload, including AAA grade games. Transcoding of any number of sessions is no different in this aspect.

**Comment by binarymelon** [comment]
I'm guess I'm wondering if plex may fallback to software transcoding if the limit is hit instead of slowing down the existing hardware transcodes.

**Comment by Snawoot** [comment]
As far as I know Plex for Windows currently doesn't work with this patch.

Plex for Linux by default has no HW decode capability (but [there exist hack](https://forums.plex.tv/t/hardware-accelerated-decode-nvidia-for-linux/233510/285) which enables it) and most likely CPU will be your bottleneck either way, at least because of audio processing. This way offloading all video encoding to GPU is still your best bet. Even if GPU somehow gets maxed out before CPU does and it is possible to perform (very few) additional transcodings on CPU, this also may happen with Quadro cards having unlimited NVENC sessions from scratch (P2000 and above) and it's up to applications how to manage such situations. So, again it's not up to this patch what to do with sessions.

In practical terms it's even hard to say how much sessions GPU is capable to convert because it varies very much from properties of incoming and outgoing video streams, therefore putting any constant limit is not viable even for performance goals.
