### ISSUE TITLE
New driver support (version 555.85)

### ISSUE THREAD

**Issue by kirk29974** [keylase/nvidia-patch#797]
**Please provide details about your environment (please complete the following information)**
- Nvidia driver version: [555.85]
- GPU Model: [e.g. GTX 1650]
- OS: [Windows 11]

Good evening everyone, have any of you developed the 2 patch files for the drivers in question?

**Comment by sgeraldes** [comment]
No longer needed. Looks like R555 doesn't have this limitation.

**Comment by theyosh** [comment]
FYI: I do hit a limit at 8 transcoding actions at the same time without patching. Testing according to: https://github.com/keylase/nvidia-patch/wiki/Verify-NVENC-patch#linux fails with 9 , but works with 8.

Also, it looks like the limit is now globally. Because when I start 1 ffmpeg process with 8 transcoding actions, I cannot start another. It will fail on the first transcoding stream.

So it looks like that for at least at Linux with version 555.42.02 has a global limit of 8 transcoding actions.

**Comment by SjoerdV** [comment]
@theyosh what can you say about the need/not-need for the fbc patch?

**Comment by theyosh** [comment]
@SjoerdV I do not know. I run on a headless server. So I do not need the fbc patch. Never used. So I can't say if that patch is still needed. I only use my nvidia card for (live) video transcoding to multiple bitrates. And that works for me.

**Comment by hpmueller1971** [comment]
Seems to official, the [nvenc-matrix](https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new) has been updated to 8 sessions...

**Comment by trebory6** [comment]
So wait, THAT is why this patch hasn't been updated?

Didn't this patch remove ALL restrictions, not just expand it to 8? 

I need to remove all restrictions. I run a personal IPTV server that uses NVENC to encode each channel as it's viewed. 

There is some leakage with the software, so if I change the channel 8 times it gives me an error saying I've reached the limit of streams being encoded. I have to wait several minutes. This doesn't even take into account if I have more than one TV in my apartment connected to the IPTV server at once. 

With this patch it was a non-issue, but with the official Nvidia update it limits it to just 8 sessions.

**Comment by Jaybonaut** [comment]
If possible, it would be wonderful if the patches would continue to lift the limit to (I believe it was) 32.  I appreciate all the hard work done so far on this project and please let us know if this is still a possibility.

**Comment by hpmueller1971** [comment]
@trebory6 i'm sure it will be updated by people that know what they are actually doing, but if you cannot wait, try this one:

`["555.42.02"]='s/\xe8\x25\x43\xfe\xff\x85\xc0\x41\x89\xc4/\xe8\x25\x43\xfe\xff\x29\xc0\x41\x89\xc4/g'`

made with find_bytecode.sh (one byte difference that changes sometimes in the last 30+ versions), seems to work, but not sure if it's really unlimited...

/hp

**Comment by jailuthra** [comment]
@hpmueller1971 that's for linux, this issue is for windows driver

@trebory6 @Jaybonaut it might still be possible to remove limit from 8 to max hw supported streams.. but someone has to reverse engineer the new drivers, or debug why the patch application is failing (see #794 )

I will try to do it when I get time. If your workflow depends so strongly on this, please feel free to contribute by sending patches :)

**Comment by reloxx13** [comment]
> So wait, THAT is why this patch hasn't been updated? Because people think 8 sessions is enough to not continue developing this patch

No, the automated generated patch does not work on latest driver dll, and ao far noone found a fix. Please stop ranting on guessings.
