### ISSUE TITLE
Question: activate 10 bit color in OpenGL not in Full screen?

### ISSUE THREAD

**Issue by ValZapod** [keylase/nvidia-patch#93]
Hello,

You can read about it there https://forums.guru3d.com/threads/since-when-did-nvidia-allow-10-bit-colour-on-non-pro-cards.401773/page-3
Maybe you are familiar enough with the driver to do smth...

**Comment by Snawoot** [comment]
Hello!

There is little to no chance we can do something with it. I didn't even heard about 10 bit color mode till these days. But I'll keep this issue open just in case if people with same problem have something to say or even bring new ideas.

**Comment by CHEF-KOCH** [comment]
10-Bit support was already added back in the [200 series ](https://nvidia.custhelp.com/app/answers/detail/a_id/3011/~/10-bit-per-color-support-on-nvidia-geforce-gpus) it can be enabled via Nvidia control panel ->Display -> Change Resolution -> Under Point 3 chose the second option here which allows you to choose 8 (8bit+FRC)/10 Bit. A demo is available [here](http://www.necdisplay.com/documents/Software/NEC_10_bit_video_Windows_demo.zip). 

The reason why nVidia soft-locked it is that you need to meat the specific requirements like DP & a Monitor which supports it otherwise you might get flickering or other strange color problems. Pro cards are used/needed for OpenGL 10-Bit Modes. The normal cards using D3D 10-Bit Mode under fullscreen exclusive mode the soft-lock basically affects 10 bit for games while OpenGL (as said) need the "Pro" cards for e.g. Photoshop (I tried to unlock it and Photoshop CS just crashes). 

The only reliable method I saw so far is to manipulate EDID on your monitor to fool the driver. If you manipulate the driver it still can be blocked (on HDMI no one has bypassed it from what I know) because the check looks for the specific EDID information first.

In a nutshell:
* Only workstation cards output true 10 bit color for both Direct X and OpenGL. Geforce cards will support 8+2 dithered in some applications. At least this is the case for 900 series and below.
* As far as Pascal goes. It will support 10/12 bit color in Direct X driven applications however OpenGL will still use 8 bit color. You will still need a Quadro with workstation drivers to achieve 10 bit in OpenGL.

Reference:
* http://nvidia.custhelp.com/app/answers/detail/a_id/3049/~/how-to-enable-30-bit-color-on-windows-platforms
* https://support.microsoft.com/en-ca/help/4040263/windows-10-hdr-advanced-color-settings
* http://nvidia.custhelp.com/app/answers/detail/a_id/3011/
* https://www.144hzmonitors.com/list-hdr-monitors/
* https://www.tonymacx86.com/threads/true-10-bit-with-adobe-photoshop-is-really-possible-with-pascal-gtx.221040/
* https://forums.geforce.com/default/topic/923466/10-bit-color-output-on-consumer-cards/
* https://www.techpowerup.com/reviews/NVIDIA/GeForce_GTX_1080/3.html
* https://forums.overclockers.co.uk/threads/enabling-full-hdr-via-nvidia-control-panel.18825061/

Paper:
* http://www.nvidia.com/docs/IO/40049/TB-04701-001_v02_new.pdf

Tests:
* http://forum.doom9.org/showthread.php?t=172128
* http://www.necdisplay.com/documents/Software/NEC_10_bit_video_Windows_demo.zip

MacOS:
* http://resxtreme.com/

EDID (Monitor "hack"):
* http://en.community.dell.com/support-forums/peripherals/f/3529/t/19615254

**Comment by ValZapod** [comment]
@CHEF-KOCH 
I will just quote for you

> As far as I know, in Windows, 10-bit OpenGL (for software like Photoshop, Premiere and others) is a feature exclusive to the Quadro line. On Linux and MacOS the GeForce line has this feature enabled for some time. I had also read AnandTech's review stating that Nvidia only allows 10-bit DirectX (windowed and fullscreen) and OpenGL (fullscreen only). What created the doubt was when Linus said he wanted to do HDR and 10-bit workstations using GeForce. As they use Adobe Premiere and it uses OpenGL, maybe this feature has been added via the driver recently. 

Also nvidea was very bad in the past. For example integer scalling and 3D LUT transformation works only in linux.
You must understand that if 10 bit is working in full screen and windows by directX and openGL and only openGL not in fullscreen dedicated mode is not working, than it is an again the same. Ok? 

Ah, yeah. References.
https://linustechtips.com/main/topic/812134-geforce-cards-and-10-bit-opengl/

**Comment by ValZapod** [comment]
@Snawoot @CHEF-KOCH 
Oh my, I suppose now it is supported with latest drivers)))
https://www.nvidia.com/en-us/geforce/news/gamescom-2019-game-ready-driver/

Scroll to 30 bit color support! Yey!
